### ISSUE TITLE
Can't start a game - Cannot run program "xdg-open"

### ISSUE THREAD

**Issue by Estugon** [software-challenge/gui#77]
### Was ist passiert?

Whenever a new game is started the gui is stuck in the "Das Spiel startet..." screen.
When opening the logs in the gui following error is shown:

![image](https://user-images.githubusercontent.com/17209524/137524713-ed1c8535-a442-4111-8805-6337edf45877.png)

System: 
 * Windows 10
 * Openjdk 17

### Dein Betriebssystem?

Windows

### Logs

```shell
18:50:10 WARN               sc.server.Configuration - Could not find server.properties at G:\Programmieren\SoftwareChallenge\Ostseeschach\server.properties, will use default values!
18:50:10 INFO   sc.server.network.NewClientListener - Listening on port 13050 for incoming connections.
18:50:10 DEBUG             sc.server.ServiceManager - Spawning thread for new service (name=NewClientListener, daemon=true)
18:50:10 DEBUG             sc.server.ServiceManager - Spawning thread for new service (name=ClientManager, daemon=true)
18:50:10 INFO       sc.server.network.ClientManager - ClientManager running
18:50:13 DEBUG      sc.gui.controller.AppController - Requested View change from START -> GAME_CREATION
18:50:16 DEBUG      sc.gui.controller.AppController - Requested View change from GAME_CREATION -> GAME_LOADING
18:50:16 INFO   sc.networking.clients.XStreamClient - Creating TCP Network for localhost:13050
18:50:16 INFO   sc.server.network.NewClientListener - A Client connected...
18:50:17 INFO       sc.server.network.ClientManager - Delegating new client to ClientManager...
18:50:17 INFO   sc.server.network.NewClientListener - Added Client Client@4ecf8765 to ReadyQueue.
18:50:17 INFO       sc.server.network.ClientManager - Delegation done
18:50:17 INFO   sc.networking.clients.XStreamClient - Creating TCP Network for localhost:13050
18:50:17 INFO   sc.server.network.NewClientListener - A Client connected...
18:50:17 INFO       sc.server.network.ClientManager - Delegating new client to ClientManager...
18:50:17 INFO   sc.server.network.NewClientListener - Added Client Client@53d9608d to ReadyQueue.
18:50:17 INFO       sc.server.network.ClientManager - Delegation done
18:50:17 INFO   sc.networking.clients.XStreamClient - Creating TCP Network for localhost:13050
18:50:17 INFO   sc.server.network.NewClientListener - A Client connected...
18:50:17 INFO              sc.server.network.Client - Client authenticated as administrator
18:50:17 INFO       sc.server.network.ClientManager - Delegating new client to ClientManager...
18:50:17 INFO   sc.server.network.NewClientListener - Added Client Client@39f19632 to ReadyQueue.
18:50:17 INFO       sc.server.network.ClientManager - Delegation done
18:50:17 DEBUG                  sc.gui.LobbyManager - Starting new game (paused: false, players: [Player(name=Spieler 1, client=sc.gui.controller.client.GuiClient@2f118d5c type Beispiel-Computerspieler on localhost:13050), Player(name=Spieler 2, client=sc.gui.controller.client.GuiClient@6fd7917b type Mensch on localhost:13050)])
18:50:17 DEBUG     sc.server.gaming.GameRoomManager - Adding room with id 2b9ad239-566e-423f-a829-a821121faa40
18:50:17 WARN             sc.server.gaming.GameRoom - PAUSE is already false, dropping request
18:50:17 INFO   sc.server.gaming.ReservationManager - Reservation b404f9df-8184-4a94-9d3b-932718fef79e was redeemed.
18:50:17 DEBUG            sc.server.gaming.GameRoom - startIfReady called
18:50:17 INFO             sc.server.gaming.GameRoom - Game not ready yet: Game(players=[ONE(Spieler 1), TWO(Spieler 2)], gameState=GameState R0T0 -> Rot (Bernsteine {}))
18:50:17 INFO   sc.server.gaming.ReservationManager - Reservation 3da1870d-edb7-41ca-ae12-14821e69ac45 was redeemed.
18:50:17 DEBUG            sc.server.gaming.GameRoom - startIfReady called
18:50:17 DEBUG    sc.framework.plugins.AbstractGame - Notifying sc.server.gaming.GameRoom@44834ad0 about new game state
18:50:17 ERROR    sc.framework.plugins.AbstractGame - NewState Notification caused an exception
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:96)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:485)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1278)
	at com.thoughtworks.xstream.XStream$3.writeToStream(XStream.java:2023)
	at com.thoughtworks.xstream.core.util.CustomObjectOutputStream.writeObjectOverride(CustomObjectOutputStream.java:87)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
	at sc.networking.clients.XStreamClient.sendObject(XStreamClient.java:187)
	at sc.networking.clients.XStreamClient.send(XStreamClient.java:168)
	at sc.server.gaming.GameRoom.lambda$observerBroadcast$3(GameRoom.java:132)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at sc.server.gaming.GameRoom.observerBroadcast(GameRoom.java:132)
	at sc.server.gaming.GameRoom.onStateChanged(GameRoom.java:145)
	at sc.framework.plugins.AbstractGame.notifyOnNewState(AbstractGame.kt:187)
	at sc.framework.plugins.AbstractGame.next(AbstractGame.kt:108)
	at sc.framework.plugins.AbstractGame.start(AbstractGame.kt:98)
	at sc.server.gaming.GameRoom.start(GameRoom.java:229)
	at sc.server.gaming.GameRoom.startIfReady(GameRoom.java:225)
	at sc.server.gaming.GameRoom.fillSlot(GameRoom.java:203)
	at sc.server.gaming.ReservationManager.redeemReservationCode(ReservationManager.java:38)
	at sc.server.Lobby.onRequest(Lobby.kt:45)
	at sc.server.network.Client.onObject(Client.java:110)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:114)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:50:17 INFO     sc.framework.plugins.AbstractGame - Sending MoveRequest to player ONE(Spieler 1)
18:50:17 DEBUG          sc.framework.plugins.Player - Move requested from ONE(Spieler 1)
18:50:17 INFO             sc.server.gaming.GameRoom - Updating Status to ACTIVE (was: CREATED)
18:50:17 INFO             sc.server.gaming.GameRoom - Started Game(players=[ONE(Spieler 1), TWO(Spieler 2)], gameState=GameState R0T0 -> Rot (Bernsteine {}))
18:50:17 ERROR  sc.networking.clients.XStreamClient - Unknown Communication Error
java.lang.IllegalStateException: Received move request before GameState!
	at sc.gui.controller.client.InternalGameHandler.calculateMove(GuiClient.kt:37)
	at sc.player.PlayerClient.apply(PlayerClient.kt:31)
	at sc.player.PlayerClient.apply(PlayerClient.kt:24)
	at sc.networking.clients.LobbyClient.onObject(LobbyClient.java:85)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:114)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:50:17 WARN   sc.networking.clients.XStreamClient - Client@53d9608d disconnected (Cause: LOST_CONNECTION, Exception: {})
java.io.EOFException: null
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2102)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:505)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:102)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:50:17 INFO   sc.networking.clients.XStreamClient - Stopping XStream-Receive id:38 of Client@53d9608d
18:50:17 WARN   sc.networking.clients.XStreamClient - LobbyClient@711dc516 disconnected (Cause: UNKNOWN, Exception: {})
java.lang.IllegalStateException: Received move request before GameState!
	at sc.gui.controller.client.InternalGameHandler.calculateMove(GuiClient.kt:37)
	at sc.player.PlayerClient.apply(PlayerClient.kt:31)
	at sc.player.PlayerClient.apply(PlayerClient.kt:24)
	at sc.networking.clients.LobbyClient.onObject(LobbyClient.java:85)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:114)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:50:17 WARN   sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
18:50:17 INFO   sc.networking.clients.XStreamClient - Stopping XStream-Receive id:39 of LobbyClient@711dc516
18:50:17 WARN   sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
18:50:17 DEBUG             sc.networking.TcpNetwork - Closing TcpNetwork{socket=Socket[addr=localhost/127.0.0.1,port=13050,localport=3619]}
18:50:17 DEBUG             sc.networking.TcpNetwork - Closing TcpNetwork{socket=Socket[addr=/127.0.0.1,port=3619,localport=13050]}
18:50:17 INFO       sc.server.network.ClientManager - Removing client Client@53d9608d from client manager
18:50:17 INFO             sc.server.gaming.GameRoom - Removing ONE(Spieler 1) from sc.server.gaming.GameRoom@44834ad0
18:50:17 INFO     sc.framework.plugins.AbstractGame - Stopping Game(players=[ONE(Spieler 1), TWO(Spieler 2)], gameState=GameState R0T0 -> Rot (Bernsteine {}))
18:50:17 DEBUG                   sc.plugin2022.Game - Calculating score for ONE(Spieler 1)
18:50:17 INFO    sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
18:50:17 DEBUG                   sc.plugin2022.Game - Calculating score for TWO(Spieler 2)
18:50:17 INFO             sc.server.gaming.GameRoom - Updating Status to OVER (was: ACTIVE)
18:50:17 INFO             sc.server.gaming.GameRoom - Game(players=[ONE(Spieler 1), TWO(Spieler 2)], gameState=GameState R0T0 -> Rot (Bernsteine {})) is over (regular=false)
18:50:17 WARN   sc.networking.clients.XStreamClient - Writing on a closed Stream -> dropped the packet (tried to send package of type RoomPacket)
18:50:17 WARN   sc.networking.clients.XStreamClient - Client@4ecf8765 disconnected (Cause: LOST_CONNECTION, Exception: {})
java.io.EOFException: null
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2102)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:505)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:102)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:50:17 WARN   sc.networking.clients.XStreamClient - LobbyClient@5b93c84d disconnected (Cause: PROTOCOL_ERROR, Exception: {})
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.EnumMap
converter           : com.thoughtworks.xstream.converters.enums.EnumMapConverter
message[1]          : Could not initialize class com.thoughtworks.xstream.converters.enums.EnumMapConverter$Reflections
converter[1]        : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[2]          : Unable to make private void java.util.EnumMap.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException accessible: module java.base does not "opens java.util" to unnamed module @2f2b1bab
converter[2]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[3]          : Unable to make field transient java.util.Set java.util.AbstractMap.keySet accessible: module java.base does not "opens java.util" to unnamed module @2f2b1bab
class               : sc.plugin2022.GameState
required-type       : sc.plugin2022.GameState
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 79
class[1]            : sc.protocol.room.MementoMessage
required-type[1]    : sc.protocol.room.MementoMessage
class[2]            : sc.protocol.room.RoomPacket
required-type[2]    : sc.protocol.room.RoomPacket
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:485)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1431)
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2105)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:505)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:102)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
18:50:17 INFO   sc.networking.clients.XStreamClient - Stopping XStream-Receive id:36 of Client@4ecf8765
18:50:17 WARN   sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
18:50:17 INFO   sc.networking.clients.XStreamClient - Stopping XStream-Receive id:37 of LobbyClient@5b93c84d
18:50:17 WARN   sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
18:50:17 DEBUG            sc.server.gaming.GameRoom - Saving replay to G:\Programmieren\SoftwareChallenge\Ostseeschach\replays\replay_swc_2022_ostseeschach_2021-10-15_18-50-17_Spieler_1_Spieler_2.xml
18:50:17 DEBUG             sc.networking.TcpNetwork - Closing TcpNetwork{socket=Socket[addr=localhost/127.0.0.1,port=13050,localport=3618]}
18:50:17 DEBUG             sc.networking.TcpNetwork - Closing TcpNetwork{socket=Socket[addr=/127.0.0.1,port=3618,localport=13050]}
18:50:17 INFO       sc.server.network.ClientManager - Removing client Client@4ecf8765 from client manager
18:50:17 INFO     sc.networking.clients.LobbyClient - Received game result: GameResult(winner=null, scores=[Spieler 1(cause=LEFT, reason='Der Spieler hat das Spiel verlassen', parts=[Siegpunkte=0, Bernsteine=0, Figur vorne=7]), Spieler 2(cause=REGULAR, reason='', parts=[Siegpunkte=2, Bernsteine=0, Figur vorne=7])])
18:50:17 DEBUG            sc.server.gaming.GameRoom - Kicking clients and observers
18:50:17 WARN   sc.networking.clients.XStreamClient - Writing on a closed Stream -> dropped the packet (tried to send package of type RemovedFromGame)
18:50:17 WARN   sc.networking.clients.XStreamClient - Writing on a closed Stream -> dropped the packet (tried to send package of type RemovedFromGame)
18:50:17 INFO     sc.networking.clients.LobbyClient - Received RemovedFromGame
18:50:17 INFO     sc.networking.clients.LobbyClient - Left 2b9ad239-566e-423f-a829-a821121faa40
18:50:21 DEBUG                 sc.util.DesktopUtils - Opening G:\Programmieren\SoftwareChallenge\Ostseeschach\log with xdg-open
```

**Comment by xeruf** [comment]
Ah, das eigentliche Problem dahinter wird bereits behoben ;) https://github.com/software-challenge/backend/pull/407

**Comment by anarchuser** [comment]
Sollte das Spiel unter Windows überhaupt `xdg-open` verwenden?

**Comment by xeruf** [comment]
Ein weiterer Fehler im Zusammenhang dazu wurde nun auch behoben: https://github.com/software-challenge/gui/commit/296c42864b1a09fd79ae0be1882fbabb2b5e295b
