### ISSUE TITLE
GUI 24.1.3 startet unter macOS nicht

### ISSUE THREAD

**Issue by SKoschnicke** [software-challenge/gui#97]
### Was ist passiert?

Ich habe die JRE von Adoptium heruntergeladen https://adoptium.net/en-GB/temurin/releases/?variant=openjdk11&jvmVariant=hotspot&os=mac&arch=aarch64

```
% java -version
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)
```
Dann habe ich die GUI mit folgendem Befehl gestartet:
```
java -jar software-challenge-gui-24.1.3-os.x.jar
```
Der Start funktioniert leider nicht. Logs sind unten.

### Dein Betriebssystem?

MacOS

### Logs

```shell
07:44:20,521 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version ?
07:44:20,522 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - No custom configurators were discovered as a service.
07:44:20,522 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
07:44:20,523 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
07:44:20,537 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
07:44:20,537 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
07:44:20,546 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 15 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
07:44:20,546 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
07:44:20,547 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
07:44:20,547 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [/Users/sven/Downloads/logback.xml]
07:44:20,547 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
07:44:20,551 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/sven/Downloads/software-challenge-gui-24.1.3-os.x.jar!/logback.xml]
07:44:20,555 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6f45df59 - URL [jar:file:/Users/sven/Downloads/software-challenge-gui-24.1.3-os.x.jar!/logback.xml] is not of type file
07:44:20,605 |-INFO in ch.qos.logback.core.model.processor.TimestampModelHandler - Using current interpretation time, i.e. now, as time reference.
07:44:20,622 |-INFO in ch.qos.logback.core.model.processor.TimestampModelHandler - Adding property to the context with key="time" and value="09-22T074420" to the LOCAL scope
07:44:20,624 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
07:44:20,624 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [sc.util.TidyFileAppender]
07:44:20,640 |-WARN in sc.util.TidyFileAppender[FILE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
07:44:20,640 |-WARN in sc.util.TidyFileAppender[FILE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
07:44:20,640 |-WARN in sc.util.TidyFileAppender[FILE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
07:44:20,640 |-INFO in sc.util.TidyFileAppender[FILE] - File property is set to [log/game-server_09-22T074420.log]
07:44:20,641 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
07:44:20,641 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:44:20,642 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
07:44:20,642 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
07:44:20,642 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
07:44:20,642 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
07:44:20,644 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [sc] to INFO
07:44:20,644 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [sc.gui] to DEBUG
07:44:20,644 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [sc.networking.clients.XStreamClient] to INFO
07:44:20,644 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
07:44:20,644 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
07:44:20,644 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
07:44:20,644 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@38e79ae3 - End of configuration.
07:44:20,645 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@63070bab - Registering current configuration as safe fallback point
07:44:20,645 |-INFO in ch.qos.logback.classic.util.ContextInitializer@58ea606c - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 98 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY

Sep 22, 2023 7:44:20 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @9d344a5'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/sven/.openjfx/cache/17/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/sven/.openjfx/cache/17/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Unknown Source)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/sven/.openjfx/cache/17/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/sven/.openjfx/cache/17/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Unknown Source)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SKoschnicke** [comment]
Leider auch noch bei Version 24.1.5

**Comment by SKoschnicke** [comment]
Wahrscheinlich gleiches Problem wie in #96
